blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogView, BlogCreateView, BlogUpdateView, BlogDeleteView, toggle_activity, \
    BlogPublishedView, BlogDetailView

app_name = BlogConfig.name

# url адресация в приложении Blog
urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('published/', BlogPublishedView.as_view(), name='blog_published'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('<str:slug>/', BlogDetailView.as_view(), name='blog_view'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from unidecode import unidecode

NULLABLE = {'blank': True, 'null': True}


# Создание модели Blog
class Blog(models.Model):
    name = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, verbose_name='Slug')
    content = models.TextField(**NULLABLE, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/media/blog/blog', **NULLABLE, verbose_name="Превью")
    date_create = models.DateTimeField(**NULLABLE, verbose_name='Дата создания')
    published = models.BooleanField(default=False, verbose_name="Опубликован")
    count_views = models.IntegerField(default=0, verbose_name='Количество просмотров')

    # Автоматическое формирование slug и date_create
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.name))
        if not self.pk:
            self.date_create = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

    # Мета данные: отображаемые имена моделей
    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, ListView, DetailView

from blog.models import Blog


# CBV на отображение главной страницы приложения
class BlogView(TemplateView):
    template_name = 'blog/blog.html'
    extra_context = {
        'title': 'Блог'
    }

    # Загрузка контента на страницу
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Blog.objects.all()
        return context_data


# CBV на загрузку опубликованного контента
class BlogPublishedView(TemplateView):
    template_name = 'blog/blog_published.html'
    extra_context = {
        'title': 'Блог'
    }

    # Загрузка контента на страницу
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = Blog.objects.all()
        return context_data


# CBV на создание нового блога
class BlogCreateView(CreateView):
    model = Blog
    fields = ('name', 'content', 'preview')
    success_url = reverse_lazy('blog:blog')


# CBV на изменение существующего блога
class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('name', 'content', 'preview')

    def get_success_url(self):
        # Получаем объект, который был отредактирован
        edited_object = self.object
        # Получаем URL-адрес страницы просмотра объекта, который был отредактирован
        return reverse('blog:blog_view', args=[edited_object.slug])


# CBV на удаление блога
class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog')


# CBV на просмотр выбранного блога
class BlogDetailView(DetailView):
    model = Blog

    def get(self, request, *args, **kwargs):
        # Получаем объект блога
        blog = self.get_object()
        # Увеличиваем счетчик просмотров на 1
        blog.count_views += 1
        blog.save()
        return super().get(request, *args, **kwargs)

    # фильтрация объектов по указанному slug адресу
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(slug=self.kwargs.get('slug'))
        return queryset

    # загрузка контента на страницу
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Название блога: "{self.object.name}"'
        context['category_pk'] = self.object.pk
        return context


# Контролер на публикацию/де-публикацию блога
def toggle_activity(request, pk):
    blog_item = get_object_or_404(Blog, pk=pk)
    if blog_item.published:
        blog_item.published = False
    else:
        blog_item.published = True

    blog_item.save()

    return redirect(reverse('blog:blog'))

blog/templates/blog/blog.html
{% extends 'catalog/base.html' %}

{% block content %}
<a href="{% url 'blog:blog_published' %}"
   class="p-2 btn btn-outline-info col-lg-12 mb-4">Список опубликованных статей</a>
<div class="row text-center">
    <div class="col-12 mb-5">
        <a href="{% url 'blog:create' %}" class="btn btn-primary">Создать новый блог</a>
    </div>
    {% for object in object_list %}
        {% include 'blog/includes/inc_blog.html' %}
    {% endfor %}
</div>

{% endblock %}

blog/templates/blog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    Удаление блога
                </div>
            <div class="card-body">

                {% csrf_token %}
                <p>Действительно хотите удалить блог {{ object.name }}?</p>
                <button type="submit" class="btn btn-outline-danger">
                        Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'blog:blog' %}">Отмена</a>
            </div>
            </div>
        </div>
    </form>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags_blog %}
{% block content %}

    <div class="row">

    {% if perms.blog.add_blog %}
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="#">Добавить блог</a>
        </div>
    {% endif %}

    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top"
                src="{{ object.photo|mymedia_blog }}"
             alt="Card image cap">
        <div class="card-body">
          <p class="card-text">{{ object.name|title }}</p>
            <span class="text text-muted"> {{ object.date_create|default:'-' }}</span>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
            </div>
          </div>
            <div class="card-footer">
                Просмотры: {{ object.count_views }}
                <a class="btn btn-outline-dark" href="{% url 'blog:blog_update' object.pk %}">Изменить</a>
                <a class="btn btn-outline-danger float-right" href="{% url 'blog:blog_delete' object.pk %}">Удалить</a>
            </div>
            {% if object.published %}
                <a class="btn btn-warning" href="{% url 'blog:toggle_activity' object.pk %}"> Убрать с публикации</a>
            {% else %}
                <a class="btn btn-success" href="{% url 'blog:toggle_activity' object.pk %}"> Опубликовать</a>
            {% endif %}
        </div>
      </div>
    </div>

    </div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {% if object %}
                        Редактирование блога
                    {% else %}
                        Создание блога
                    {% endif %}
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Добавить
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

blog/templates/blog/blog_published.html
{% extends 'catalog/base.html' %}

{% block content %}
<a href="{% url 'blog:blog_published' %}"
   class="p-2 btn btn-outline-info col-lg-12 mb-4">Список опубликованных статей</a>
<div class="row text-center">
    <div class="col-12 mb-5">
        <a href="{% url 'blog:create' %}" class="btn btn-primary">Создать новый блог</a>
    </div>
    {% for object in object_list %}
        {% if object.published %}
            {% include 'blog/includes/inc_blog.html' %}
        {% endif %}
    {% endfor %}
</div>

{% endblock %}