blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogView, BlogCreateView, BlogUpdateView, BlogDeleteView, toggle_activity, \
    BlogPublishedView, BlogDetailView

app_name = BlogConfig.name

# url адресация в приложении Blog
urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('published/', BlogPublishedView.as_view(), name='blog_published'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('<str:slug>/', BlogDetailView.as_view(), name='blog_view'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# Импорт необходимых модулей
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView, verify_email, reset_password
from users.apps import UsersConfig

# Установка имени приложения
app_name = UsersConfig.name

# Определение URL-шаблонов
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),  # URL для входа в систему
    path('logout/', LogoutView.as_view(), name='logout'),  # URL для выхода из системы
    path('register/', RegisterView.as_view(), name='register'),  # URL для регистрации
    path('profile/', ProfileView.as_view(), name='profile'),  # URL для профиля пользователя
    path('verify-email/', verify_email, name='verify_email'),  # URL для подтверждения почты пользователя
    path('reset-password/', reset_password, name='reset_password'),
]

users/models.py
import uuid
from random import random

from django.contrib.auth.models import AbstractUser
from django.db import models

from src.constants import NULLABLE


class User(AbstractUser):
    # Удаляем поле "username", так как мы используем "email" в качестве уникального идентификатора пользователя
    username = None

    # Поле для хранения почты пользователя
    email = models.EmailField(unique=True, verbose_name='Почта')

    # Поле для хранения номера телефона пользователя
    phone = models.CharField(max_length=35, verbose_name='Телефон', **NULLABLE)

    # Поле для хранения аватара пользователя
    avatar = models.ImageField(upload_to='users/avatars', verbose_name='Аватар', **NULLABLE)

    # Поле для хранения страны пользователя
    country = models.CharField(max_length=35, verbose_name='Страна', **NULLABLE)

    # Поле для хранения верификационного кода пользователя, который генерируется рандомно при создании пользователя
    verification_code = models.CharField(max_length=35, verbose_name='Код', **NULLABLE)

    # Поле для хранения значения верифицирован ли пользователь. По умолчанию - False
    is_verified = models.BooleanField(default=False, verbose_name='Верификация')

    # Указываем поле "email" как поле для входа в систему
    USERNAME_FIELD = "email"

    # Поля, которые должны быть заполнены при создании пользователя
    REQUIRED_FIELDS = []

    # Переопределяем метод save для автоматической генерации verification_code при создании пользователя
    def save(self, *args, **kwargs):
        # Генерируем уникальный код с помощью функции uuid4()
        self.verification_code = str(uuid.uuid4())[:8]
        super().save(*args, **kwargs)

users/forms.py
# Импорт необходимых модулей
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import User


# Форма регистрации пользователя
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


# Форма профиля пользователя
class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'avatar', 'country')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Скрываем поле пароля
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from src.functions import send_mail, generate_password
from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


# Класс для регистрации пользователя
class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verify_email')

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data['email']
        # получаем код верификации из базы данных пользователя
        verification_code = f"Ваш код верификации: {User.objects.get(email=email).verification_code}"
        send_mail(email, 'Код подтверждения', verification_code)
        return response


# Класс для обновления профиля пользователя
class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    # Получение объекта пользователя
    def get_object(self, queryset=None):
        return self.request.user


# функция для вывода страницы с одним полем для подтверждения верификации пользователя
def verify_email(request):
    if request.method == 'POST':
        verification_code = request.POST.get('verification_code')
        try:
            user = User.objects.get(verification_code=verification_code)
            if user.verification_code == verification_code:
                user.is_active = True
                user.is_verified = True
                user.save()
                return redirect('catalog:start_form')
        except User.DoesNotExist:
            messages.error(request, 'Неверный код верификации')
    return render(request, 'users/verify_email.html')


# Функция для восстановления пароля пользователя
def reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = generate_password(length=10)
            # перезаписываем пароль пользователя
            user.set_password(new_password)
            user.save()
            new_password_text = f'Ваш новый пароль:\n{new_password}'
            # отправляем письмо с новым паролем пользователя
            send_mail(email, 'Восстановление пароля', new_password_text)
            return redirect('users:login')
        except User.DoesNotExist:
            messages.error(request, 'Неверный email')
    return render(request, 'users/recover_password.html')

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Вход</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                      {% if form.errors %}
                        <p class="error-message">Неверный пароль.
                        <a class="p-2 btn btn-outline-danger" href="{% url 'users:reset_password' %}">Восстановить пароль</a></p>
                      {% endif %}
                    <button type="submit" class="btn btn-outline-success">Войти</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/recover_password.html
{% extends 'catalog/base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <label for="email">Почта:</label>
    <input type="text" name="email" id="email">
    <button type="submit" class="btn btn-outline-success">Восстановить пароль</button>
  </form>
  {% if error_message %}
    <p>{{ error_message }}</p>
  {% endif %}
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Регистрация</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">Регистрация</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Профиль</h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-success">Сохранить</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

users/templates/users/verify_email.html
{% extends 'catalog/base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <label for="verification_code">Код верификации:</label>
    <input type="text" name="verification_code" id="verification_code">
    <button type="submit" class="btn btn-outline-success">Подтвердить</button>
  </form>
  {% if error_message %}
    <p>{{ error_message }}</p>
  {% endif %}
{% endblock %}