blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogView, BlogCreateView, BlogUpdateView, BlogDeleteView, toggle_activity, \
    BlogPublishedView, BlogDetailView

app_name = BlogConfig.name

# url адресация в приложении Blog
urlpatterns = [
    path('', BlogView.as_view(), name='blog'),
    path('published/', BlogPublishedView.as_view(), name='blog_published'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
    path('<str:slug>/', BlogDetailView.as_view(), name='blog_view'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import (ContactsView, IndexView, ProductListView, ProductCreateView, ProductUpdateView,
                           CategoryCreateView, ProductDeleteView, ProductDetailView)

# Конфигурационное имя приложения
app_name = CatalogConfig.name

# Ссылки на страницы приложения Catalog
urlpatterns = [
    # Главная страница
    path('', IndexView.as_view(), name='start_form'),
    # Страница контактов
    path('contacts/', ContactsView.as_view(), name='contacts'),
    # Список товаров
    path('products/<int:pk>/', ProductListView.as_view(), name='product_list'),
    # Создание товара
    path('products/create/', ProductCreateView.as_view(), name='create_product'),
    # Редактирование товара
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    # Удаление товара
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    # Создание категории
    path('category/create/', CategoryCreateView.as_view(), name='create_category'),
    # Просмотр товара
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# Импорт необходимых модулей
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, ProfileView, verify_email, reset_password
from users.apps import UsersConfig

# Установка имени приложения
app_name = UsersConfig.name

# Определение URL-шаблонов
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),  # URL для входа в систему
    path('logout/', LogoutView.as_view(), name='logout'),  # URL для выхода из системы
    path('register/', RegisterView.as_view(), name='register'),  # URL для регистрации
    path('profile/', ProfileView.as_view(), name='profile'),  # URL для профиля пользователя
    path('verify-email/', verify_email, name='verify_email'),  # URL для подтверждения почты пользователя
    path('reset-password/', reset_password, name='reset_password'),
]

catalog/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from src.constants import NULLABLE
from users.models import User


# Описание модели Продуктов
class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')
    image = models.ImageField(upload_to='products', **NULLABLE, verbose_name='изображение')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='категория')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='цена за покупку')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    date_modified = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')
    # Поле для хранения пользователя, который создал продукт
    owner = models.ForeignKey(User, on_delete=models.PROTECT, **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='признак публикации', **NULLABLE)

    def __str__(self):
        return self.name

    # Метаданные для обозначения модели
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


# Описание модели Категорий
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(**NULLABLE, verbose_name='описание')

    def __str__(self):
        return self.name

    # Метаданные для обозначения модели
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


# Описание модели Версий
class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.PositiveIntegerField(validators=[MinValueValidator(1)], verbose_name='Номер версии')
    name = models.CharField(max_length=100, verbose_name='Имя версии')
    is_active = models.BooleanField(default=False, verbose_name='Признак текущей версии')

    def __str__(self):
        return f"{self.product.name} - Версия {self.number}"

    # Метаданные для обозначения модели
    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from .models import Product, Category, Version


# Форма для продукта
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'image', 'category', 'price', 'is_published']

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        # Список запрещенных слов
        forbidden_words = ['казино', 'криптовалюта', 'крипта',
                           'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        # Проверяем наличие запрещенных слов в названии или описании продукта
        for word in forbidden_words:
            if word in name.lower() or word in description.lower():
                raise forms.ValidationError("Нельзя добавлять запрещенные слова в название или описание продукта.")


# Форма для категории
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        # Список запрещенных слов
        forbidden_words = ['казино', 'криптовалюта', 'крипта',
                           'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        # Проверяем наличие запрещенных слов в названии или описании категории
        for word in forbidden_words:
            if word in name.lower() or word in description.lower():
                raise forms.ValidationError("Нельзя добавлять запрещенные слова в название или описание продукта.")


# Форма для версии продукта
class ProductVersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['number', 'name', 'is_active']

catalog/views.py
# Импорт необходимых модулей
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView
from catalog.forms import ProductForm, CategoryForm, ProductVersionForm
from django.shortcuts import reverse
from django import forms
from .models import Product, Version, Category
from django.db.models import Case, When, CharField
from .services import get_cache_object_list


# Класс стартовой страницы приложения Catalog
class IndexView(TemplateView):
    template_name = 'catalog/start_form.html'
    extra_context = {
        'title': 'Склад товаров',
        'view': 'Просмотр товаров'
    }

    def get_context_data(self, **kwargs):
        # Получение данных контекста
        context_data = super().get_context_data(**kwargs)
        context_data['object_list'] = get_cache_object_list()
        return context_data


# Страница с контактными данными
class ContactsView(View):
    def get(self, request):
        return render(request, 'catalog/contacts.html')

    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'name: {name}, email: {email}, message: {message}')
        return render(request, 'catalog/contacts.html')


# Класс страницы с продуктами по выбранным категориям
class ProductListView(ListView):
    model = Product
    template_name = 'product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        # Получение всех продуктов по выбранной категории
        queryset = super().get_queryset()
        queryset = queryset.filter(category=self.kwargs.get('pk'))
        active_versions = Version.objects.filter(is_active=True)
        return queryset.prefetch_related('version_set').annotate(active_version=Case(
            When(version__is_active=True, then='version__name'),
            default=None,
            output_field=CharField()
        ))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_moderator'] = self.request.user.groups.filter(name='Модератор').exists()
        return context


# Класс страницы для создания продукта
class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'create_product.html'

    def get_context_data(self, **kwargs):
        # Получение данных контекста
        context = super().get_context_data(**kwargs)
        context['version_form'] = ProductVersionForm(prefix='version')
        return context

    def form_valid(self, form):
        # Проверка валидности формы
        self.object = form.save(commit=False)
        if self.request.user.is_authenticated:
            self.object.owner = self.request.user
        self.object.save()
        product = form.save(commit=False)
        product.name = form.cleaned_data['name']
        product.save()
        version_form = ProductVersionForm(self.request.POST, prefix='version')
        if version_form.is_valid():
            version = version_form.save(commit=False)
            version.product = product
            version.save()
        return redirect(reverse('catalog:product_list', kwargs={'pk': form.cleaned_data['category'].pk}))

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.groups.filter(name='Модератор').exists():
            # Скрыть поле публикации, если ты не модератор
            form.fields['is_published'].widget = forms.HiddenInput()
        return form


# Класс страницы для редактирования продукта
class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'update_product.html'

    def test_func(self):
        product = self.get_object()
        return self.request.user == product.owner or self.request.user.groups.filter(name='Модератор').exists()

    def get_success_url(self):
        product = self.get_object()
        return reverse('catalog:product_list', kwargs={'pk': product.category.pk})

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if not self.request.user.groups.filter(name='Модератор').exists():
            # Скрыть поле публикации, если ты не модератор
            form.fields['is_published'].widget = forms.HiddenInput()
        return form


# Класс страницы для удаления продукта
class ProductDeleteView(UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'delete_product.html'

    def get_success_url(self):
        product = self.get_object()
        return reverse('catalog:product_list', kwargs={'pk': product.category.pk})

    def test_func(self):
        product = self.get_object()
        return self.request.user == product.owner or self.request.user.groups.filter(name='Модератор').exists()


# Класс страницы для создания категории
class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'create_category.html'

    def form_valid(self, form):
        # Проверка валидности формы
        self.object = form.save()
        return redirect(reverse('catalog:product_list', kwargs={'pk': self.object.pk}))


# Класс страницы для детального просмотра продукта
class ProductDetailView(TemplateView):
    template_name = 'catalog/product_detail.html'

    def get_context_data(self, **kwargs):
        # Получение данных контекста
        context_data = super().get_context_data(**kwargs)
        context_data['product'] = Product.objects.get(pk=self.kwargs.get('pk'))
        return context_data

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">{{ title }}</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:blog' %}">Блог</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-danger" href="{% url 'users:logout' %}">Выйти</a>
            <a class="p-2 btn btn-outline-warning" href="{% url 'users:profile' %}">Профиль</a>
        {% else %}
            <a class="p-2 btn btn-outline-success" href="{% url 'users:login' %}">Войти</a>
            <a class="p-2 btn btn-outline-warning" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
{#    <p class="lead">{{ title }} - здесь вы найдёте всё, что надо!</p>#}
</div>

<div class="container">
    {% block content %}
    {% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                {{ title }}
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>

catalog/templates/catalog/contact_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Заполните ваши данные:</h1>
<br>
<form method="post">
    {% csrf_token %}
    <input type="text" name="name"><br>
    <input type="email" name="email"><br>
    <textarea name="message"></textarea><br>
    <input type="submit" value="Отправить"><br>
</form>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Краснодарский край, г.Новороссийск</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Введите сообщение" required></textarea>
                        </div>
                    </form>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

catalog/templates/catalog/create_category.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="container">
      <div class="text-center">
        <h1 class="mb-5">Создание категории товара</h1>
      </div>
    <form method="post">
      {% csrf_token %}
        <div class="border p-4">
            {{ form.as_p }}
        </div>
      <button type="submit" class="btn btn-primary">Создать</button>
    </form>
  </div>

{% endblock %}

catalog/templates/catalog/create_product.html
{% extends 'catalog/base.html' %}

{% load my_tags %}

{% block content %}
<div class="container">
    <div class="text-center">
     <h1 class="mb-5">Создание продукта</h1>
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <div class="border p-4">
                    <div class="text-center">
                        <h2 class="mb-5">Параметры продукта</h2>
                    </div>
                    {{ form.as_p }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="border p-4">
                    <div class="text-center">
                        <h2 class="mb-5">Версия продукта</h2>
                    </div>
                    {{ version_form.as_p }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
  <h1>{{ product.name }}</h1>
    <p>Описание: {{ product.description }}</p>
    <img class="card-img-top"
        src="{{ product.image|mymedia }}"
         alt="Card image cap">
    <p>Категория: {{ product.category }}</p>
    <p>Дата создания: {{ product.date_created }}</p>
    <p>Дата модификации: {{ product.date_modified }}</p>
    <p>Создатель: {{ product.owner.email }}</p>
    <p>Цена: {{ product.price }}</p>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <a href="{% url 'catalog:create_product' %}" class="btn btn-primary">Создать продукт</a>
<div class="row text-center">
    {% for product in products %}
       {% if product.is_published or is_moderator %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name|title }}</h4>
                    </div>
                    <img class="card-img-top"
                            src="{{ product.image|mymedia }}"
                         alt="Card image cap">
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ product.price }} р.</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            <li>- {{ product.description|slice:":100" }}</li>
                        </ul>
                        {% if product.active_version %}
                            <p>Активная версия: {{ product.active_version }}</p>
                        {% else %}
                            <p>Товар отсутствует</p>
                        {% endif %}
                        {% if product.owner == request.user or is_moderator %}
                            <a href="{% url 'catalog:update_product' product.pk %}" class="btn btn-primary">Редактировать</a>
                            <a href="{% url 'catalog:delete_product' product.pk %}" class="btn btn-danger">Удалить</a>
                        {% endif %}
                    <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-outline-primary">Просмотр</a>
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row text-center">
    {% for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name|title }}</h4>
            </div>
            <img class="card-img-top"
                    src="{{ object.image|mymedia }}"
                 alt="Card image cap">
            <div class="card-body">
                <h1 class="card-title pricing-card-title">{{ object.price }} р.</h1>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- {{ object.description|slice:":100" }}</li>
                </ul>
                <button type="button" class="btn btn-lg btn-block btn-outline-primary">{{ view }}</button>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

catalog/templates/catalog/start_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <!-- Создание продукта -->
    <div class="text-end">
        <a href="{% url 'catalog:create_product' %}" class="btn btn-outline-primary mb-2">Создать продукт</a>
    </div>

    <!-- Создание категории -->
    <div class="text-end">
        <a href="{% url 'catalog:create_category' %}" class="btn btn-outline-primary mb-2">Создать категорию</a>
    </div>

    <!-- Вывод объектов -->
    <div class="row text-center">
        {% for object in object_list %}
            {% include 'catalog/includes/inc_forms.html' %}
        {% endfor %}
    </div>
{% endblock %}